paths:
  /Employees:
    post:
      tags:
        - Employee
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Employee.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
    put:
      tags:
        - Employee
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Employee.upsert__put_Employees
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
    patch:
      tags:
        - Employee
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Employee.upsert__patch_Employees
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
    get:
      tags:
        - Employee
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Employee.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
      deprecated: false
  /Employees/replaceOrCreate:
    post:
      tags:
        - Employee
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Employee.replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
  /Employees/upsertWithWhere:
    post:
      tags:
        - Employee
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: Employee.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
  '/Employees/{id}/exists':
    get:
      tags:
        - Employee
      summary: Check whether a model instance exists in the data source.
      operationId: 'Employee.exists__get_Employees_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Employees/{id}':
    head:
      tags:
        - Employee
      summary: Check whether a model instance exists in the data source.
      operationId: 'Employee.exists__head_Employees_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Employee
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Employee.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
    delete:
      tags:
        - Employee
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Employee.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Employee
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Employee.prototype.updateAttributes__put_Employees_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Employee'
        - name: id
          in: path
          description: Employee id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
    patch:
      tags:
        - Employee
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Employee.prototype.updateAttributes__patch_Employees_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Employee'
        - name: id
          in: path
          description: Employee id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
  '/Employees/{id}/replace':
    post:
      tags:
        - Employee
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: Employee.replaceById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
  /Employees/findOne:
    get:
      tags:
        - Employee
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Employee.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Employee'
      deprecated: false
  /Employees/update:
    post:
      tags:
        - Employee
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Employee.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Employees/count:
    get:
      tags:
        - Employee
      summary: Count instances of the model matched by where from the data source.
      operationId: Employee.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
definitions:
  Employee:
    properties:
      id:
        type: number
        format: double
      name:
        type: string
    required:
      - id
      - name
    additionalProperties: false
  x-any:
    properties: {}
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: leave
  version: 1.0.0
  title: Leave
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
